export interface ChallengeImageSet {
  original: string[];
  attacked: string[];
}

// Image lists for pixel attack challenge
export const PIXEL_ATTACK_IMAGES: ChallengeImageSet = {
  original: [
    '01_idx0_true8_pred8.png',
    '02_idx1_true4_pred4.png',
    '03_idx2_true8_pred8.png',
    '04_idx3_true7_pred7.png',
    '05_idx4_true7_pred7.png',
    '06_idx5_true0_pred0.png',
    '07_idx6_true6_pred6.png',
    '08_idx7_true2_pred2.png',
    '09_idx8_true7_pred7.png',
    '10_idx9_true4_pred4.png',
    '11_idx10_true3_pred3.png',
    '12_idx11_true9_pred9.png',
    'failed_0_true8_pred8.png',
    'failed_1_true4_pred4.png',
    'failed_2_true8_pred8.png',
    'failed_3_true7_pred7.png',
    'failed_4_true7_pred7.png',
  ],
  attacked: [
    'attack_0_attacked_pred9.png',
    'attack_1_attacked_pred2.png',
    'attack_2_attacked_pred6.png',
    'attack_3_attacked_pred9.png',
    'attack_4_attacked_pred7.png',
  ],
};

// Image lists for rotation attack challenge
export const ROTATE_ATTACK_IMAGES: ChallengeImageSet = {
  original: [
    '01_idx0_true8_pred8.png',
    '02_idx1_true4_pred4.png',
    '03_idx2_true8_pred8.png',
    '04_idx3_true7_pred7.png',
    '05_idx4_true7_pred7.png',
    '06_idx5_true0_pred0.png',
    '07_idx6_true6_pred6.png',
    '08_idx7_true2_pred2.png',
    '09_idx8_true7_pred7.png',
    '10_idx9_true4_pred4.png',
    '11_idx10_true3_pred3.png',
    '12_idx11_true9_pred9.png',
  ],
  attacked: [
    'rotate_attack_0_attacked_pred2_rot15deg.png',
    'rotate_attack_1_attacked_pred2_rot15deg.png',
    'rotate_attack_2_attacked_pred2_rot-10deg.png',
    'rotate_attack_3_attacked_pred5_rot15deg.png',
    'rotate_attack_4_attacked_pred2_rot-15deg.png',
  ],
};

// Image lists for shift attack challenge
export const SHIFT_ATTACK_IMAGES: ChallengeImageSet = {
  original: [
    '01_idx0_true8_pred8.png',
    '02_idx1_true4_pred4.png',
    '03_idx2_true8_pred8.png',
    '04_idx3_true7_pred7.png',
    '05_idx4_true7_pred7.png',
    '06_idx5_true0_pred0.png',
    '07_idx6_true6_pred6.png',
    '08_idx7_true2_pred2.png',
    '09_idx8_true7_pred7.png',
    '10_idx9_true4_pred4.png',
    '11_idx10_true3_pred3.png',
    '12_idx11_true9_pred9.png',
  ],
  attacked: [
    'shift_attack_0_attacked_pred2_dx-5_dy-4.png',
    'shift_attack_1_attacked_pred8_dx-5_dy-3.png',
    'shift_attack_2_attacked_pred2_dx-3_dy5.png',
    'shift_attack_3_attacked_pred2_dx-1_dy-3.png',
    'shift_attack_4_attacked_pred2_dx2_dy-5.png',
  ],
};

// Image lists for random noise attack challenge (MNIST)
export const NOISE_ATTACK_IMAGES: ChallengeImageSet = {
  original: [
    '01_idx0_true8_pred8.png',
    '02_idx1_true4_pred4.png',
    '03_idx2_true8_pred8.png',
    '04_idx3_true7_pred7.png',
    '05_idx4_true7_pred7.png',
    '06_idx5_true0_pred0.png',
    '07_idx6_true6_pred6.png',
    '08_idx7_true2_pred2.png',
    '09_idx8_true7_pred7.png',
    '10_idx9_true4_pred4.png',
    '11_idx10_true3_pred3.png',
    '12_idx11_true9_pred9.png',
    'noise_attack_0_original_true0.png',
    'noise_attack_1_original_true1.png',
    'noise_attack_2_original_true9.png',
    'noise_attack_3_original_true1.png',
    'noise_attack_4_original_true3.png',
    'failed_noise_0_original_true8.png',
    'failed_noise_1_original_true4.png',
    'failed_noise_2_original_true8.png',
    'failed_noise_3_original_true7.png',
    'failed_noise_4_original_true7.png',
  ],
  attacked: [
    'noise_attack_0_attacked_pred2_sigma0.25.png',
    'noise_attack_1_attacked_pred7_sigma0.25.png',
    'noise_attack_2_attacked_pred4_sigma0.25.png',
    'noise_attack_3_attacked_pred2_sigma0.25.png',
    'noise_attack_4_attacked_pred2_sigma0.25.png',
    'failed_noise_0_attacked_pred8_sigma0.2.png',
    'failed_noise_1_attacked_pred4_sigma0.25.png',
    'failed_noise_2_attacked_pred8_sigma0.15.png',
    'failed_noise_3_attacked_pred7_sigma0.2.png',
    'failed_noise_4_attacked_pred7_sigma0.25.png',
  ],
};

// Image lists for blur attack challenge (MNIST)
export const BLUR_ATTACK_IMAGES: ChallengeImageSet = {
  original: [
    '01_idx0_true8_pred8.png',
    '02_idx1_true4_pred4.png',
    '03_idx2_true8_pred8.png',
    '04_idx3_true7_pred7.png',
    '05_idx4_true7_pred7.png',
    '06_idx5_true0_pred0.png',
    '07_idx6_true6_pred6.png',
    '08_idx7_true2_pred2.png',
    '09_idx8_true7_pred7.png',
    '10_idx9_true4_pred4.png',
    '11_idx10_true3_pred3.png',
    '12_idx11_true9_pred9.png',
    'blur_attack_0_original_true7.png',
    'blur_attack_1_original_true4.png',
    'blur_attack_2_original_true3.png',
    'blur_attack_3_original_true7.png',
    'blur_attack_4_original_true9.png',
    'failed_blur_0_original_true8.png',
    'failed_blur_1_original_true4.png',
    'failed_blur_2_original_true8.png',
    'failed_blur_3_original_true7.png',
    'failed_blur_4_original_true7.png',
  ],
  attacked: [
    'blur_attack_0_attacked_pred1_k7_s2.0.png',
    'blur_attack_1_attacked_pred1_k7_s2.0.png',
    'blur_attack_2_attacked_pred1_k7_s2.0.png',
    'blur_attack_3_attacked_pred1_k7_s2.0.png',
    'blur_attack_4_attacked_pred1_k7_s2.0.png',
    'failed_blur_0_attacked_pred8_k7_s0.5.png',
    'failed_blur_1_attacked_pred4_k5_s1.5.png',
    'failed_blur_2_attacked_pred8_k5_s1.0.png',
    'failed_blur_3_attacked_pred7_k5_s1.5.png',
    'failed_blur_4_attacked_pred7_k7_s2.0.png',
  ],
};

// Image lists for adversarial patch challenge (MNIST)
export const PATCH_ATTACK_IMAGES: ChallengeImageSet = {
  original: [
    '01_idx0_true8_pred8.png',
    '02_idx1_true4_pred4.png',
    '03_idx2_true8_pred8.png',
    '04_idx3_true7_pred7.png',
    '05_idx4_true7_pred7.png',
    '06_idx5_true0_pred0.png',
    '07_idx6_true6_pred6.png',
    '08_idx7_true2_pred2.png',
    '09_idx8_true7_pred7.png',
    '10_idx9_true4_pred4.png',
    '11_idx10_true3_pred3.png',
    '12_idx11_true9_pred9.png',
    'patch_attack_0_original_true8.png',
    'patch_attack_1_original_true8.png',
    'patch_attack_2_original_true7.png',
    'patch_attack_3_original_true7.png',
    'patch_attack_4_original_true0.png',
    'failed_patch_0_original_true4.png',
  ],
  attacked: [
    'patch_attack_0_attacked_pred3_x10_y6_h8_w8.png',
    'patch_attack_1_attacked_pred5_x15_y4_h8_w8.png',
    'patch_attack_2_attacked_pred3_x17_y13_h8_w8.png',
    'patch_attack_3_attacked_pred3_x12_y13_h8_w8.png',
    'patch_attack_4_attacked_pred2_x7_y5_h8_w8.png',
    'failed_patch_0_attacked_pred4_x20_y6_h8_w8.png',
  ],
};

// Image lists for pixel (3x3) attack challenge (ImageNet)
export const IMAGENET_PIXEL_ATTACK_IMAGES: ChallengeImageSet = {
  original: [
    'original_0_true0.png',
    'original_1_true0.png',
    'original_2_true0.png',
    'original_3_true0.png',
    'original_4_true0.png',
    'original_5_true0.png',
    'original_6_true0.png',
    'original_7_true0.png',
    'original_8_true0.png',
    'original_9_true0.png',
    'original_10_true0.png',
    'original_11_true0.png',
    'original_12_true0.png',
    'original_13_true0.png',
    'original_14_true0.png',
    'original_15_true0.png',
    'original_16_true0.png',
    'original_17_true1.png',
    'original_18_true1.png',
    'original_19_true1.png',
    '3x3_0_original_true0.png',
    '3x3_1_original_true0.png',
    '3x3_2_original_true0.png',
    '3x3_3_original_true0.png',
    '3x3_4_original_true0.png',
    '3x3_5_original_true1.png',
    '3x3_6_original_true1.png',
    '3x3_7_original_true1.png',
    '3x3_8_original_true1.png',
    '3x3_9_original_true1.png',
  ],
  attacked: [
    '3x3_0_attacked_pred151_c2_x97_y53_extreme.png',
    '3x3_1_attacked_pred130_c1_x93_y30_extreme.png',
    '3x3_2_attacked_pred43_c1_x47_y51_extreme.png',
    '3x3_3_attacked_pred13_c0_x84_y18_extreme.png',
    '3x3_4_attacked_pred113_c1_x74_y21_extreme.png',
    '3x3_5_attacked_pred113_c1_x77_y27_extreme.png',
    '3x3_6_attacked_pred7_c1_x22_y59_extreme.png',
    '3x3_7_attacked_pred118_c0_x104_y42_extreme.png',
    '3x3_8_attacked_pred10_c1_x93_y17_extreme.png',
    '3x3_9_attacked_pred41_c0_x11_y9_extreme.png',
  ],
};

// Image lists for blur attack challenge (ImageNet)
export const IMAGENET_BLUR_ATTACK_IMAGES: ChallengeImageSet = {
  original: [
    'original_0_true0.png',
    'original_1_true0.png',
    'original_2_true0.png',
    'original_3_true0.png',
    'original_4_true0.png',
    'original_5_true0.png',
    'original_6_true0.png',
    'original_7_true0.png',
    'original_8_true0.png',
    'original_9_true0.png',
    'original_10_true0.png',
    'original_11_true0.png',
    'original_12_true0.png',
    'original_13_true0.png',
    'original_14_true0.png',
    'original_15_true0.png',
    'original_16_true0.png',
    'original_17_true1.png',
    'original_18_true1.png',
    'original_19_true1.png',
    'blur_attack_0_original_true0.png',
    'blur_attack_1_original_true0.png',
    'blur_attack_2_original_true0.png',
    'blur_attack_3_original_true0.png',
    'blur_attack_4_original_true0.png',
    'blur_attack_5_original_true1.png',
    'blur_attack_6_original_true1.png',
    'blur_attack_7_original_true1.png',
    'blur_attack_8_original_true1.png',
    'blur_attack_9_original_true1.png',
  ],
  attacked: [
    'blur_attack_0_attacked_pred72_sigma1p75.png',
    'blur_attack_1_attacked_pred42_sigma1p50.png',
    'blur_attack_2_attacked_pred130_sigma2p00.png',
    'blur_attack_3_attacked_pred176_sigma0p75.png',
    'blur_attack_4_attacked_pred25_sigma2p00.png',
    'blur_attack_5_attacked_pred139_sigma1p50.png',
    'blur_attack_6_attacked_pred95_sigma1p75.png',
    'blur_attack_7_attacked_pred88_sigma2p00.png',
    'blur_attack_8_attacked_pred122_sigma1p75.png',
    'blur_attack_9_attacked_pred44_sigma1p50.png',
    'failed_blur_0_true0_pred0_sigma1p75.png',
    'failed_blur_1_true0_pred0_sigma1p50.png',
    'failed_blur_2_true0_pred0_sigma1p75.png',
    'failed_blur_3_true0_pred0_sigma0p75.png',
    'failed_blur_4_true0_pred0_sigma1p00.png',
  ],
};

// Image lists for random noise attack challenge (ImageNet)
export const IMAGENET_NOISE_ATTACK_IMAGES: ChallengeImageSet = {
  original: [
    'original_0_true0.png',
    'original_1_true0.png',
    'original_2_true0.png',
    'original_3_true0.png',
    'original_4_true0.png',
    'original_5_true0.png',
    'original_6_true0.png',
    'original_7_true0.png',
    'original_8_true0.png',
    'original_9_true0.png',
    'original_10_true0.png',
    'original_11_true0.png',
    'original_12_true0.png',
    'original_13_true0.png',
    'original_14_true0.png',
    'original_15_true0.png',
    'original_16_true0.png',
    'original_17_true1.png',
    'original_18_true1.png',
    'original_19_true1.png',
    'noise_attack_0_original_true0.png',
    'noise_attack_1_original_true0.png',
    'noise_attack_2_original_true0.png',
    'noise_attack_3_original_true0.png',
    'noise_attack_4_original_true0.png',
    'noise_attack_5_original_true0.png',
    'noise_attack_6_original_true0.png',
    'noise_attack_7_original_true0.png',
    'noise_attack_8_original_true0.png',
    'noise_attack_9_original_true0.png',
  ],
  attacked: [
    'noise_attack_0_attacked_pred102_sigma0p10.png',
    'noise_attack_1_attacked_pred199_sigma0p08.png',
    'noise_attack_2_attacked_pred152_sigma0p10.png',
    'noise_attack_3_attacked_pred13_sigma0p08.png',
    'noise_attack_4_attacked_pred13_sigma0p04.png',
    'noise_attack_5_attacked_pred196_sigma0p08.png',
    'noise_attack_6_attacked_pred13_sigma0p06.png',
    'noise_attack_7_attacked_pred13_sigma0p06.png',
    'noise_attack_8_attacked_pred196_sigma0p08.png',
    'noise_attack_9_attacked_pred13_sigma0p04.png',
  ],
};

// Image lists for adversarial patch challenge (ImageNet)
export const IMAGENET_PATCH_ATTACK_IMAGES: ChallengeImageSet = {
  original: [
    'original_0_true0.png',
    'original_1_true0.png',
    'original_2_true0.png',
    'original_3_true0.png',
    'original_4_true0.png',
    'original_5_true0.png',
    'original_6_true0.png',
    'original_7_true0.png',
    'original_8_true0.png',
    'original_9_true0.png',
    'original_10_true0.png',
    'original_11_true0.png',
    'original_12_true0.png',
    'original_13_true0.png',
    'original_14_true0.png',
    'original_15_true0.png',
    'original_16_true0.png',
    'original_17_true1.png',
    'original_18_true1.png',
    'original_19_true1.png',
    'patch_attack_0_original_true0.png',
    'patch_attack_1_original_true0.png',
    'patch_attack_2_original_true0.png',
    'patch_attack_3_original_true0.png',
    'patch_attack_4_original_true0.png',
    'patch_attack_5_original_true0.png',
    'patch_attack_6_original_true0.png',
    'patch_attack_7_original_true0.png',
    'patch_attack_8_original_true0.png',
    'patch_attack_9_original_true0.png',
  ],
  attacked: [
    'patch_attack_0_attacked_pred87_x86_y74.png',
    'patch_attack_1_attacked_pred129_x26_y77.png',
    'patch_attack_2_attacked_pred72_x14_y22.png',
    'patch_attack_3_attacked_pred36_x41_y45.png',
    'patch_attack_4_attacked_pred130_x92_y3.png',
    'patch_attack_5_attacked_pred26_x58_y0.png',
    'patch_attack_6_attacked_pred85_x34_y9.png',
    'patch_attack_7_attacked_pred176_x79_y11.png',
    'patch_attack_8_attacked_pred113_x57_y87.png',
    'patch_attack_9_attacked_pred47_x22_y27.png',
    'failed_patch_0_true0_pred0_x15_y65.png',
    'failed_patch_1_true0_pred0_x51_y9.png',
  ],
};

// Image lists for rotation attack challenge (ImageNet)
export const IMAGENET_ROTATE_ATTACK_IMAGES: ChallengeImageSet = {
  original: [
    'original_0_true0.png',
    'original_1_true0.png',
    'original_2_true0.png',
    'original_3_true0.png',
    'original_4_true0.png',
    'original_5_true0.png',
    'original_6_true0.png',
    'original_7_true0.png',
    'original_8_true0.png',
    'original_9_true0.png',
    'original_10_true0.png',
    'original_11_true0.png',
    'original_12_true0.png',
    'original_13_true0.png',
    'original_14_true0.png',
    'original_15_true0.png',
    'original_16_true0.png',
    'original_17_true1.png',
    'original_18_true1.png',
    'original_19_true1.png',
    'rotate_attack_0_original_true0.png',
    'rotate_attack_1_original_true0.png',
    'rotate_attack_2_original_true0.png',
    'rotate_attack_3_original_true0.png',
    'rotate_attack_4_original_true0.png',
    'rotate_attack_5_original_true0.png',
    'rotate_attack_6_original_true0.png',
    'rotate_attack_7_original_true0.png',
    'rotate_attack_8_original_true0.png',
    'rotate_attack_9_original_true0.png',
  ],
  attacked: [
    'rotate_attack_0_attacked_pred141_rot-10deg.png',
    'rotate_attack_1_attacked_pred189_rot3deg.png',
    'rotate_attack_2_attacked_pred83_rot10deg.png',
    'rotate_attack_3_attacked_pred93_rot10deg.png',
    'rotate_attack_4_attacked_pred83_rot-15deg.png',
    'rotate_attack_5_attacked_pred93_rot15deg.png',
    'rotate_attack_6_attacked_pred104_rot5deg.png',
    'rotate_attack_7_attacked_pred189_rot5deg.png',
    'rotate_attack_8_attacked_pred113_rot-2deg.png',
    'rotate_attack_9_attacked_pred164_rot-3deg.png',
    'failed_rotate_0_true0_pred0_rot-2deg.png',
    'failed_rotate_1_true0_pred0_rot2deg.png',
    'failed_rotate_2_true0_pred0_rot-15deg.png',
    'failed_rotate_3_true0_pred0_rot-15deg.png',
  ],
};

// Image lists for shift attack challenge (ImageNet)
export const IMAGENET_SHIFT_ATTACK_IMAGES: ChallengeImageSet = {
  original: [
    'original_0_true0.png',
    'original_1_true0.png',
    'original_2_true0.png',
    'original_3_true0.png',
    'original_4_true0.png',
    'original_5_true0.png',
    'original_6_true0.png',
    'original_7_true0.png',
    'original_8_true0.png',
    'original_9_true0.png',
    'original_10_true0.png',
    'original_11_true0.png',
    'original_12_true0.png',
    'original_13_true0.png',
    'original_14_true0.png',
    'original_15_true0.png',
    'original_16_true0.png',
    'original_17_true1.png',
    'original_18_true1.png',
    'original_19_true1.png',
    'shift_attack_0_original_true0.png',
    'shift_attack_1_original_true0.png',
    'shift_attack_2_original_true0.png',
    'shift_attack_3_original_true0.png',
    'shift_attack_4_original_true0.png',
    'shift_attack_5_original_true0.png',
    'shift_attack_6_original_true0.png',
    'shift_attack_7_original_true0.png',
    'shift_attack_8_original_true0.png',
    'shift_attack_9_original_true0.png',
  ],
  attacked: [
    'shift_attack_0_attacked_pred99_dx-2_dy8.png',
    'shift_attack_1_attacked_pred59_dx-6_dy-2.png',
    'shift_attack_2_attacked_pred83_dx2_dy6.png',
    'shift_attack_3_attacked_pred130_dx8_dy-8.png',
    'shift_attack_4_attacked_pred152_dx6_dy-4.png',
    'shift_attack_5_attacked_pred186_dx8_dy4.png',
    'shift_attack_6_attacked_pred93_dx8_dy-8.png',
    'shift_attack_7_attacked_pred130_dx8_dy-4.png',
    'shift_attack_8_attacked_pred93_dx-6_dy8.png',
    'shift_attack_9_attacked_pred104_dx2_dy-4.png',
    'failed_shift_0_true0_pred0_dx-2_dy6.png',
  ],
};
